export enum IconTypes {
  'AttachFile' = 'AttachFile',
  'Cross' = 'Cross',
  'Check' = 'Check',
  'Checked' = 'Checked',
  'Date' = 'Date',
  'Dropdown' = 'Dropdown',
  'Facebook' = 'Fb',
  'GitHub' = 'GitHub',
  'Google' = 'Google',
  'Language' = 'Language',
  'Login' = 'Login',
  'Mail' = 'Mail',
  'Menu' = 'Menu',
  'Place' = 'Place',
  'Register' = 'Register',
  'Telegram' = 'Telegram',
  'Time' = 'Time',
  'Twitter' = 'Twitter',
  'Youtube' = 'Youtube'
}
