name: Node Github CI

on:
  push:
    branches:
      - AlexandraMor8-patch-1

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and build
      run: |
        npm install
        npm run build
      env:
        CI: true

#   deploy:
#     needs: [build]
#     runs-on: ubuntu-latest

#     steps:
#     - name: SSH and deploy node app
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: ${{ secrets.SSH_USERNAME }}
#         key: ${{ secrets.SSH_KEY }}
#         port: 22
#         script: |
#           cd ~/portal
#           git pull origin main
#           npm install
#           npm run build
#           pm2 restart math-random-portal
